# Generated by Django 5.1.1 on 2024-09-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_profile_pic_remove_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('dateDebut', models.DateTimeField(auto_now_add=True)),
                ('dateFin', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('A faire', 'À faire'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], max_length=10, verbose_name='Statut')),
                ('priorite', models.CharField(choices=[('Basse', 'Basse'), ('Moyenne', 'Moyenne'), ('Haute', 'Haute')], max_length=10, verbose_name='Priorité')),
            ],
        ),
    ]
