# Generated by Django 5.1.1 on 2024-09-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_tache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
